//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory:BaseModel
    {
        
        public string Name { get; set; }
        public string Img { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string keyWords { get; set; }
        public string Path { get; set; }
        public string Deep { get; set; }
    }
}
