//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product:BaseModel
    {
        
        public string ProductTitle { get; set; }
        public string ProductMainImg { get; set; }
        public string ProductSlideImgs { get; set; }
        public string ProductDetail { get; set; }
        public string ProductSku { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public string ProductCategoryPath { get; set; }
        public string ProductSkuValues { get; set; }
        public Nullable<int> ProductBrandID { get; set; }
        public string keyWords { get; set; }
    }
}
