//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBrand:BaseModel
    {
        
        public string LogoInitials { get; set; }
        public string BrandLogo { get; set; }
        public string BrandImg { get; set; }
        public string BrandStory { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> Display { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string BrandName { get; set; }
    }
}
